apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-namespace-on-deployments
spec:
  validationFailureAction: Enforce
  rules:
    - name: must-specify-namespace
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        message: "All Deployments must specify a namespace (not use the default)."
        deny:
          conditions:
            - key: "{{ request.namespace }}"
              operator: Equals
              value: "default"
