apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-namespace
spec:
  validationFailureAction: Enforce
  rules:
    - name: require-namespace
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        message: "You must have namespace configured for all deployments"
        pattern:
          metadata:
              namespace: "?*"
